// Generated by Apple Swift version 5.0 (swiftlang-1001.0.69.5 clang-1001.0.46.3)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import AVFoundation;
@import BaiduMapSDK;
@import CoreBluetooth;
@import CoreGraphics;
@import CoreLocation;
@import CoreMedia;
@import Foundation;
@import GTSDK;
@import MBProgressHUD;
@import MessageUI;
@import ObjectiveC;
@import UIKit;
@import UserNotifications;
@import WebKit;
@import dsBridge;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="FrameworkDemo",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif


SWIFT_CLASS("_TtC13FrameworkDemo14APNsMsgManager")
@interface APNsMsgManager : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13FrameworkDemo11AudioPlayer")
@interface AudioPlayer : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class AVAudioPlayer;

@interface AudioPlayer (SWIFT_EXTENSION(FrameworkDemo)) <AVAudioPlayerDelegate>
- (void)audioPlayerDidFinishPlaying:(AVAudioPlayer * _Nonnull)player successfully:(BOOL)flag;
- (void)audioPlayerDecodeErrorDidOccur:(AVAudioPlayer * _Nonnull)player error:(NSError * _Nullable)error;
@end

@class NSCoder;

SWIFT_CLASS("_TtC13FrameworkDemo15AudioRecordView")
@interface AudioRecordView : UIView
- (void)drawRect:(CGRect)rect;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13FrameworkDemo13AudioRecorder")
@interface AudioRecorder : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class AVAudioRecorder;

@interface AudioRecorder (SWIFT_EXTENSION(FrameworkDemo)) <AVAudioRecorderDelegate>
- (void)audioRecorderDidFinishRecording:(AVAudioRecorder * _Nonnull)recorder successfully:(BOOL)flag;
- (void)audioRecorderEncodeErrorDidOccur:(AVAudioRecorder * _Nonnull)recorder error:(NSError * _Nullable)error;
@end

@class NSBundle;

SWIFT_CLASS("_TtC13FrameworkDemo23AudioRecorderController")
@interface AudioRecorderController : UIViewController
/// 系统方法
- (void)viewDidLoad;
- (void)viewWillLayoutSubviews;
- (void)didReceiveMemoryWarning;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13FrameworkDemo9BaseModel")
@interface BaseModel : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13FrameworkDemo18CircleProgressView")
@interface CircleProgressView : UIView
- (void)drawRect:(CGRect)rect;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13FrameworkDemo14DatePickerView")
@interface DatePickerView : UIView <UIGestureRecognizerDelegate, UIPickerViewDataSource, UIPickerViewDelegate>
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIGestureRecognizer;
@class UITouch;

@interface DatePickerView (SWIFT_EXTENSION(FrameworkDemo))
- (BOOL)gestureRecognizer:(UIGestureRecognizer * _Nonnull)gestureRecognizer shouldReceiveTouch:(UITouch * _Nonnull)touch SWIFT_WARN_UNUSED_RESULT;
@end



@class UIPickerView;

@interface DatePickerView (SWIFT_EXTENSION(FrameworkDemo))
- (NSInteger)numberOfComponentsInPickerView:(UIPickerView * _Nonnull)pickerView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)pickerView:(UIPickerView * _Nonnull)pickerView numberOfRowsInComponent:(NSInteger)component SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)pickerView:(UIPickerView * _Nonnull)pickerView rowHeightForComponent:(NSInteger)component SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nonnull)pickerView:(UIPickerView * _Nonnull)pickerView viewForRow:(NSInteger)row forComponent:(NSInteger)component reusingView:(UIView * _Nullable)view SWIFT_WARN_UNUSED_RESULT;
- (void)pickerView:(UIPickerView * _Nonnull)pickerView didSelectRow:(NSInteger)row inComponent:(NSInteger)component;
@end






SWIFT_CLASS("_TtC13FrameworkDemo13EventCalendar")
@interface EventCalendar : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13FrameworkDemo13EventReminder")
@interface EventReminder : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13FrameworkDemo13LoadErrorView")
@interface LoadErrorView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
@end


SWIFT_CLASS("_TtC13FrameworkDemo13MCAlertAction")
@interface MCAlertAction : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end






SWIFT_CLASS("_TtC13FrameworkDemo17MCAlertController")
@interface MCAlertController : UIViewController
- (void)viewDidDisappear:(BOOL)animated;
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end




@interface MCAlertController (SWIFT_EXTENSION(FrameworkDemo)) <UIGestureRecognizerDelegate>
- (BOOL)gestureRecognizer:(UIGestureRecognizer * _Nonnull)gestureRecognizer shouldReceiveTouch:(UITouch * _Nonnull)touch SWIFT_WARN_UNUSED_RESULT;
@end






SWIFT_CLASS("_TtC13FrameworkDemo7MapView")
@interface MapView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13FrameworkDemo17MapViewController")
@interface MapViewController : UIViewController
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class BMKUserLocation;

@interface MapViewController (SWIFT_EXTENSION(FrameworkDemo)) <BMKLocationServiceDelegate>
- (void)didUpdateBMKUserLocation:(BMKUserLocation * _Null_unspecified)userLocation;
@end

@class BMKRouteSearch;
@class BMKDrivingRouteResult;

@interface MapViewController (SWIFT_EXTENSION(FrameworkDemo)) <BMKRouteSearchDelegate>
- (void)onGetDrivingRouteResult:(BMKRouteSearch * _Null_unspecified)searcher result:(BMKDrivingRouteResult * _Null_unspecified)result errorCode:(BMKSearchErrorCode)error;
@end

@class BMKMapView;
@protocol BMKOverlay;
@class BMKOverlayView;

@interface MapViewController (SWIFT_EXTENSION(FrameworkDemo)) <BMKMapViewDelegate>
/// 定位失败后的回调
/// \param error 错误参数
///
- (void)didFailToLocateUserWithError:(NSError * _Null_unspecified)error;
/// 地图区域改变完成后
- (void)mapView:(BMKMapView * _Null_unspecified)mapView regionDidChangeAnimated:(BOOL)animated;
/// 路径规划的线路
/// \param mapView <#mapView description#>
///
/// \param overlay <#overlay description#>
///
///
/// returns:
/// <#return value description#>
- (BMKOverlayView * _Null_unspecified)mapView:(BMKMapView * _Null_unspecified)mapView viewForOverlay:(id <BMKOverlay> _Null_unspecified)overlay SWIFT_WARN_UNUSED_RESULT;
@end










SWIFT_CLASS("_TtC13FrameworkDemo7Network")
@interface Network : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13FrameworkDemo11NetworkTool")
@interface NetworkTool : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end






SWIFT_CLASS("_TtC13FrameworkDemo17SHAlertController")
@interface SHAlertController : UIAlertController
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIWindow;
@class UIApplication;

SWIFT_CLASS("_TtC13FrameworkDemo13SHAppDelegate")
@interface SHAppDelegate : UIResponder <UIApplicationDelegate>
@property (nonatomic, strong) UIWindow * _Nullable window;
/// 横竖屏相关
- (UIInterfaceOrientationMask)application:(UIApplication * _Nonnull)application supportedInterfaceOrientationsForWindow:(UIWindow * _Nullable)window SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end








@interface SHAppDelegate (SWIFT_EXTENSION(FrameworkDemo)) <BMKGeneralDelegate>
@end


@interface SHAppDelegate (SWIFT_EXTENSION(FrameworkDemo)) <UIGestureRecognizerDelegate>
/// 手势都能同时相应
- (BOOL)gestureRecognizer:(UIGestureRecognizer * _Nonnull)gestureRecognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(UIGestureRecognizer * _Nonnull)otherGestureRecognizer SWIFT_WARN_UNUSED_RESULT;
@end




@interface SHAppDelegate (SWIFT_EXTENSION(FrameworkDemo)) <GeTuiSdkDelegate>
/// SDK 启动返回CID
/// \param clientId <#clientId description#>
///
- (void)GeTuiSdkDidRegisterClient:(NSString * _Null_unspecified)clientId;
/// 个推透传回调
/// \param payloadData <#payloadData description#>
///
/// \param taskId <#taskId description#>
///
/// \param msgId <#msgId description#>
///
/// \param offLine <#offLine description#>
///
/// \param appId <#appId description#>
///
- (void)GeTuiSdkDidReceivePayloadData:(NSData * _Null_unspecified)payloadData andTaskId:(NSString * _Null_unspecified)taskId andMsgId:(NSString * _Null_unspecified)msgId andOffLine:(BOOL)offLine fromGtAppId:(NSString * _Null_unspecified)appId;
@end

@class UITapGestureRecognizer;

@interface SHAppDelegate (SWIFT_EXTENSION(FrameworkDemo))
/// 点击弹出调试view
- (void)handleSixFingerQuadrupleTapWithTapRecognizer:(UITapGestureRecognizer * _Nonnull)tapRecognizer;
@end

@class UIEvent;

@interface SHAppDelegate (SWIFT_EXTENSION(FrameworkDemo))
@property (nonatomic, readonly) BOOL canBecomeFirstResponder;
/// 后台操作
- (void)remoteControlReceivedWithEvent:(UIEvent * _Nullable)event;
@end

@class UILocalNotification;
@class UNUserNotificationCenter;
@class UNNotification;
@class UNNotificationResponse;

@interface SHAppDelegate (SWIFT_EXTENSION(FrameworkDemo)) <UNUserNotificationCenterDelegate>
/// 远程通知注册成功委托
/// \param application 
///
/// \param deviceToken <#deviceToken description#>
///
- (void)application:(UIApplication * _Nonnull)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData * _Nonnull)deviceToken;
/// 远程通知注册失败
/// \param application <#application description#>
///
/// \param error <#error description#>
///
- (void)application:(UIApplication * _Nonnull)application didFailToRegisterForRemoteNotificationsWithError:(NSError * _Nonnull)error;
/// 处理UILocalNotification的本地推送 (iOS8-10)
- (void)application:(UIApplication * _Nonnull)application didReceiveLocalNotification:(UILocalNotification * _Nonnull)notification;
/// 处理 APNs 通知点击事件 (iOS8-10)
- (void)application:(UIApplication * _Nonnull)application didReceiveRemoteNotification:(NSDictionary * _Nonnull)userInfo fetchCompletionHandler:(void (^ _Nonnull)(UIBackgroundFetchResult))completionHandler;
- (void)userNotificationCenter:(UNUserNotificationCenter * _Nonnull)center willPresentNotification:(UNNotification * _Nonnull)notification withCompletionHandler:(void (^ _Nonnull)(UNNotificationPresentationOptions))completionHandler SWIFT_AVAILABILITY(ios,introduced=10.0);
- (void)userNotificationCenter:(UNUserNotificationCenter * _Nonnull)center didReceiveNotificationResponse:(UNNotificationResponse * _Nonnull)response withCompletionHandler:(void (^ _Nonnull)(void))completionHandler SWIFT_AVAILABILITY(ios,introduced=10.0);
@end


SWIFT_CLASS("_TtC13FrameworkDemo20SHAudioPlayerManager")
@interface SHAudioPlayerManager : UIResponder
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end






SWIFT_CLASS("_TtC13FrameworkDemo20SHBaseViewController")
@interface SHBaseViewController : UIViewController
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13FrameworkDemo27SHAudioPlayerViewController")
@interface SHAudioPlayerViewController : SHBaseViewController
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end



@class UISlider;

@interface SHAudioPlayerViewController (SWIFT_EXTENSION(FrameworkDemo))
/// 拖动进度条改变值时触发
- (void)playbackSliderValueChanged:(UISlider * _Nonnull)sender;
@end


@interface SHAudioPlayerViewController (SWIFT_EXTENSION(FrameworkDemo))
@property (nonatomic, readonly) BOOL canBecomeFirstResponder;
- (void)remoteControlReceivedWithEvent:(UIEvent * _Nullable)event;
@end




SWIFT_CLASS("_TtC13FrameworkDemo26SHBaseNavigationController")
@interface SHBaseNavigationController : UINavigationController
- (void)viewDidLoad;
/// 是否支持屏幕旋转
@property (nonatomic, readonly) BOOL shouldAutorotate;
/// 支持的屏幕旋转方向
@property (nonatomic, readonly) UIInterfaceOrientationMask supportedInterfaceOrientations;
/// 状态栏样式
@property (nonatomic, readonly) UIStatusBarStyle preferredStatusBarStyle;
- (nonnull instancetype)initWithNavigationBarClass:(Class _Nullable)navigationBarClass toolbarClass:(Class _Nullable)toolbarClass OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=5.0);
- (nonnull instancetype)initWithRootViewController:(UIViewController * _Nonnull)rootViewController OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end




SWIFT_CLASS("_TtC13FrameworkDemo22SHBaseTabBarController")
@interface SHBaseTabBarController : UITabBarController
- (void)viewDidLoad;
@property (nonatomic, readonly) BOOL shouldAutorotate;
@property (nonatomic, readonly) UIInterfaceOrientationMask supportedInterfaceOrientations;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end











@interface SHBaseViewController (SWIFT_EXTENSION(FrameworkDemo)) <UIGestureRecognizerDelegate>
/// 监听侧滑返回
- (void)willMoveToParentViewController:(UIViewController * _Nullable)parent;
- (void)didMoveToParentViewController:(UIViewController * _Nullable)parent;
@end


@interface SHBaseViewController (SWIFT_EXTENSION(FrameworkDemo))
/// 返回上一页网页,如果没有上一页的网页则返回到上一个controller
- (void)popViewControlWithAnimation;
- (void)closeCurrentPage;
@end


@interface SHBaseViewController (SWIFT_EXTENSION(FrameworkDemo))
/// 状态栏的样式
@property (nonatomic, readonly) UIStatusBarStyle preferredStatusBarStyle;
/// 是否隐藏状态栏
@property (nonatomic, readonly) BOOL prefersStatusBarHidden;
@end


@interface SHBaseViewController (SWIFT_EXTENSION(FrameworkDemo))
@property (nonatomic, readonly) UIInterfaceOrientationMask supportedInterfaceOrientations;
@property (nonatomic, readonly) BOOL shouldAutorotate;
@end


SWIFT_CLASS("_TtC13FrameworkDemo29SHBaseWebLoaderViewControoler")
@interface SHBaseWebLoaderViewControoler : SHBaseViewController
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


@interface SHBaseWebLoaderViewControoler (SWIFT_EXTENSION(FrameworkDemo)) <WKUIDelegate>
@end

@class UIScrollView;

@interface SHBaseWebLoaderViewControoler (SWIFT_EXTENSION(FrameworkDemo)) <UIScrollViewDelegate>
- (void)scrollViewDidScroll:(UIScrollView * _Nonnull)scrollView;
@end






@interface SHBaseWebLoaderViewControoler (SWIFT_EXTENSION(FrameworkDemo))
- (void)popViewControlWithAnimation;
@end


@interface SHBaseWebLoaderViewControoler (SWIFT_EXTENSION(FrameworkDemo))
- (void)viewWillAppear:(BOOL)animated;
@end

@class WKWebView;
@class WKNavigationAction;
@class WKNavigationResponse;
@class WKNavigation;
@class NSURLAuthenticationChallenge;
@class NSURLCredential;

@interface SHBaseWebLoaderViewControoler (SWIFT_EXTENSION(FrameworkDemo)) <WKNavigationDelegate>
/// 跳转前
- (void)webView:(WKWebView * _Nonnull)webView decidePolicyForNavigationAction:(WKNavigationAction * _Nonnull)navigationAction decisionHandler:(void (^ _Nonnull)(WKNavigationActionPolicy))decisionHandler;
/// 跳转前的响应头数据
- (void)webView:(WKWebView * _Nonnull)webView decidePolicyForNavigationResponse:(WKNavigationResponse * _Nonnull)navigationResponse decisionHandler:(void (^ _Nonnull)(WKNavigationResponsePolicy))decisionHandler;
/// 加载失败
- (void)webView:(WKWebView * _Nonnull)webView didFailProvisionalNavigation:(WKNavigation * _Null_unspecified)navigation withError:(NSError * _Nonnull)error;
/// 加载失败
- (void)webView:(WKWebView * _Nonnull)webView didFailNavigation:(WKNavigation * _Null_unspecified)navigation withError:(NSError * _Nonnull)error;
/// 加载完成
- (void)webView:(WKWebView * _Nonnull)webView didFinishNavigation:(WKNavigation * _Null_unspecified)navigation;
/// https 支持
- (void)webView:(WKWebView * _Nonnull)webView didReceiveAuthenticationChallenge:(NSURLAuthenticationChallenge * _Nonnull)challenge completionHandler:(void (^ _Nonnull)(enum NSURLSessionAuthChallengeDisposition, NSURLCredential * _Nullable))completionHandler;
- (void)webViewWebContentProcessDidTerminate:(WKWebView * _Nonnull)webView;
@end


SWIFT_CLASS("_TtC13FrameworkDemo30SHBluetoothCharacteristicModel")
@interface SHBluetoothCharacteristicModel : BaseModel
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




SWIFT_CLASS("_TtC13FrameworkDemo22SHBluetoothDeviceModel")
@interface SHBluetoothDeviceModel : BaseModel
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




SWIFT_CLASS("_TtC13FrameworkDemo18SHBluetoothManager")
@interface SHBluetoothManager : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



@class CBPeripheral;
@class CBService;
@class CBCharacteristic;

@interface SHBluetoothManager (SWIFT_EXTENSION(FrameworkDemo)) <CBPeripheralDelegate>
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didDiscoverServices:(NSError * _Nullable)error;
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didDiscoverCharacteristicsForService:(CBService * _Nonnull)service error:(NSError * _Nullable)error;
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didUpdateNotificationStateForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didUpdateValueForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didWriteValueForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;
@end

@class CBCentralManager;

@interface SHBluetoothManager (SWIFT_EXTENSION(FrameworkDemo)) <CBCentralManagerDelegate>
- (void)centralManagerDidUpdateState:(CBCentralManager * _Nonnull)central;
- (void)centralManager:(CBCentralManager * _Nonnull)central didDiscoverPeripheral:(CBPeripheral * _Nonnull)peripheral advertisementData:(NSDictionary<NSString *, id> * _Nonnull)advertisementData RSSI:(NSNumber * _Nonnull)RSSI;
- (void)centralManager:(CBCentralManager * _Nonnull)central didConnectPeripheral:(CBPeripheral * _Nonnull)peripheral;
- (void)centralManager:(CBCentralManager * _Nonnull)central didFailToConnectPeripheral:(CBPeripheral * _Nonnull)peripheral error:(NSError * _Nullable)error;
- (void)centralManager:(CBCentralManager * _Nonnull)central didDisconnectPeripheral:(CBPeripheral * _Nonnull)peripheral error:(NSError * _Nullable)error;
@end




SWIFT_CLASS("_TtC13FrameworkDemo23SHBluetoothServiceModel")
@interface SHBluetoothServiceModel : BaseModel
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




SWIFT_CLASS("_TtC13FrameworkDemo29SHChooseLocaionViewController")
@interface SHChooseLocaionViewController : SHBaseViewController
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end



@class BMKGeoCodeSearch;
@class BMKReverseGeoCodeResult;

@interface SHChooseLocaionViewController (SWIFT_EXTENSION(FrameworkDemo)) <BMKGeoCodeSearchDelegate>
/// 返回反地理编码搜索结果
- (void)onGetReverseGeoCodeResult:(BMKGeoCodeSearch * _Null_unspecified)searcher result:(BMKReverseGeoCodeResult * _Null_unspecified)result errorCode:(BMKSearchErrorCode)error;
@end


@interface SHChooseLocaionViewController (SWIFT_EXTENSION(FrameworkDemo)) <BMKLocationServiceDelegate>
/// 已经定位
- (void)didUpdateBMKUserLocation:(BMKUserLocation * _Null_unspecified)userLocation;
@end

@class BMKPoiSearch;
@class BMKPoiResult;

@interface SHChooseLocaionViewController (SWIFT_EXTENSION(FrameworkDemo)) <BMKPoiSearchDelegate>
/// 返回检索周边的结果
- (void)onGetPoiResult:(BMKPoiSearch * _Null_unspecified)searcher result:(BMKPoiResult * _Null_unspecified)poiResult errorCode:(BMKSearchErrorCode)errorCode;
@end






@interface SHChooseLocaionViewController (SWIFT_EXTENSION(FrameworkDemo)) <BMKMapViewDelegate>
/// 定位失败后的回调
/// \param error 错误参数
///
- (void)didFailToLocateUserWithError:(NSError * _Null_unspecified)error;
/// 地图区域改变完成后
- (void)mapView:(BMKMapView * _Null_unspecified)mapView regionDidChangeAnimated:(BOOL)animated;
@end

@class UITableView;
@class UITableViewCell;

@interface SHChooseLocaionViewController (SWIFT_EXTENSION(FrameworkDemo)) <UITableViewDataSource>
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end


@interface SHChooseLocaionViewController (SWIFT_EXTENSION(FrameworkDemo)) <UITableViewDelegate>
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)scrollViewDidEndDecelerating:(UIScrollView * _Nonnull)scrollView;
@end



@class UISearchController;

@interface SHChooseLocaionViewController (SWIFT_EXTENSION(FrameworkDemo)) <UISearchControllerDelegate>
- (void)presentSearchController:(UISearchController * _Nonnull)searchController;
- (void)willPresentSearchController:(UISearchController * _Nonnull)searchController;
- (void)didPresentSearchController:(UISearchController * _Nonnull)searchController;
- (void)willDismissSearchController:(UISearchController * _Nonnull)searchController;
- (void)didDismissSearchController:(UISearchController * _Nonnull)searchController;
@end


SWIFT_CLASS("_TtC13FrameworkDemo29SHChooseLocationTableViewCell")
@interface SHChooseLocationTableViewCell : UITableViewCell
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13FrameworkDemo20SHChooseLocationView")
@interface SHChooseLocationView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end




SWIFT_CLASS("_TtC13FrameworkDemo14SHContactModel")
@interface SHContactModel : BaseModel
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13FrameworkDemo8SHDevice")
@interface SHDevice : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end





@class CLLocationManager;
@class CLHeading;

@interface SHDevice (SWIFT_EXTENSION(FrameworkDemo)) <CLLocationManagerDelegate>
/// 获得地理和地磁航向数据，从而转动地理刻度表
- (void)locationManager:(CLLocationManager * _Nonnull)manager didUpdateHeading:(CLHeading * _Nonnull)newHeading;
@end



@class UIImage;

SWIFT_CLASS("_TtC13FrameworkDemo14SHImageViewGIF")
@interface SHImageViewGIF : UIImageView
@property (nonatomic, readonly) CGSize intrinsicContentSize;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image highlightedImage:(UIImage * _Nullable)highlightedImage OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


/// 其实我们原生这边对长期回调和短期区分的作用没有那么大, 主要是对H5那边有影响
SWIFT_CLASS("_TtC13FrameworkDemo21SHJSRegisterBaseClass")
@interface SHJSRegisterBaseClass : NSObject
- (void)registerHandler;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13FrameworkDemo11SHJSAuthApi")
@interface SHJSAuthApi : SHJSRegisterBaseClass
- (void)registerHandler;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end






SWIFT_CLASS("_TtC13FrameworkDemo27SHJSBaseModalViewController")
@interface SHJSBaseModalViewController : UIViewController
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


@interface SHJSBaseModalViewController (SWIFT_EXTENSION(FrameworkDemo))
- (void)dismissModalView;
@end


SWIFT_CLASS("_TtC13FrameworkDemo26SHJSDatePickViewController")
@interface SHJSDatePickViewController : SHJSBaseModalViewController
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end






@interface SHJSDatePickViewController (SWIFT_EXTENSION(FrameworkDemo))
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
@end


SWIFT_CLASS("_TtC13FrameworkDemo13SHJSDeviceApi")
@interface SHJSDeviceApi : SHJSRegisterBaseClass <MFMailComposeViewControllerDelegate, MFMessageComposeViewControllerDelegate>
- (void)registerHandler;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end





























@class MFMailComposeViewController;

@interface SHJSDeviceApi (SWIFT_EXTENSION(FrameworkDemo))
- (void)mailComposeController:(MFMailComposeViewController * _Nonnull)controller didFinishWithResult:(MFMailComposeResult)result error:(NSError * _Nullable)error;
@end

@class MFMessageComposeViewController;

@interface SHJSDeviceApi (SWIFT_EXTENSION(FrameworkDemo))
- (void)messageComposeViewController:(MFMessageComposeViewController * _Nonnull)controller didFinishWithResult:(MessageComposeResult)result;
@end












SWIFT_CLASS("_TtC13FrameworkDemo22SHJSNaviLeftButtonView")
@interface SHJSNaviLeftButtonView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end








SWIFT_CLASS("_TtC13FrameworkDemo23SHJSNaviRightButtonView")
@interface SHJSNaviRightButtonView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end








SWIFT_CLASS("_TtC13FrameworkDemo19SHJSNaviSegmentView")
@interface SHJSNaviSegmentView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end




SWIFT_CLASS("_TtC13FrameworkDemo17SHJSNaviTitleView")
@interface SHJSNaviTitleView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end






SWIFT_CLASS("_TtC13FrameworkDemo16SHJSNavigatorApi")
@interface SHJSNavigatorApi : SHJSRegisterBaseClass
- (void)registerHandler;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end
















SWIFT_CLASS("_TtC13FrameworkDemo11SHJSPageApi")
@interface SHJSPageApi : SHJSRegisterBaseClass
- (void)registerHandler;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end











SWIFT_CLASS("_TtC13FrameworkDemo14SHJSRuntimeApi")
@interface SHJSRuntimeApi : SHJSRegisterBaseClass <CLLocationManagerDelegate>
- (void)registerHandler;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



















@class CLLocation;

@interface SHJSRuntimeApi (SWIFT_EXTENSION(FrameworkDemo))
/// 定位成功代理
- (void)locationManager:(CLLocationManager * _Nonnull)manager didUpdateLocations:(NSArray<CLLocation *> * _Nonnull)locations;
/// 定位失败代理
- (void)locationManager:(CLLocationManager * _Nonnull)manager didFailWithError:(NSError * _Nonnull)error;
@end


SWIFT_CLASS("_TtC13FrameworkDemo9SHJSUiApi")
@interface SHJSUiApi : SHJSRegisterBaseClass
- (void)registerHandler;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end














SWIFT_CLASS("_TtC13FrameworkDemo11SHJSUtilApi")
@interface SHJSUtilApi : SHJSRegisterBaseClass
- (void)registerHandler;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end































@class UIDocumentInteractionController;

@interface SHJSUtilApi (SWIFT_EXTENSION(FrameworkDemo)) <UIDocumentInteractionControllerDelegate>
- (UIViewController * _Nonnull)documentInteractionControllerViewControllerForPreview:(UIDocumentInteractionController * _Nonnull)controller SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nullable)documentInteractionControllerViewForPreview:(UIDocumentInteractionController * _Nonnull)controller SWIFT_WARN_UNUSED_RESULT;
- (CGRect)documentInteractionControllerRectForPreview:(UIDocumentInteractionController * _Nonnull)controller SWIFT_WARN_UNUSED_RESULT;
@end

@class UIDocumentPickerViewController;

@interface SHJSUtilApi (SWIFT_EXTENSION(FrameworkDemo)) <UIDocumentPickerDelegate>
/// 返回文件路径
- (void)documentPicker:(UIDocumentPickerViewController * _Nonnull)controller didPickDocumentAtURL:(NSURL * _Nonnull)url;
/// 返回文件路径
- (void)documentPicker:(UIDocumentPickerViewController * _Nonnull)controller didPickDocumentsAtURLs:(NSArray<NSURL *> * _Nonnull)urls;
@end


SWIFT_CLASS("_TtC13FrameworkDemo15SHJSWelcomeView")
@interface SHJSWelcomeView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


@interface SHJSWelcomeView (SWIFT_EXTENSION(FrameworkDemo)) <UIScrollViewDelegate>
- (void)scrollViewDidScroll:(UIScrollView * _Nonnull)scrollView;
@end




SWIFT_CLASS("_TtC13FrameworkDemo15SHLocationModel")
@interface SHLocationModel : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13FrameworkDemo14SHPopMenuModel")
@interface SHPopMenuModel : BaseModel
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13FrameworkDemo13SHPopMenuView")
@interface SHPopMenuView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end




@interface SHPopMenuView (SWIFT_EXTENSION(FrameworkDemo)) <UITableViewDelegate>
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


@interface SHPopMenuView (SWIFT_EXTENSION(FrameworkDemo)) <UITableViewDataSource>
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end


@interface SHPopMenuView (SWIFT_EXTENSION(FrameworkDemo))
- (void)drawRect:(CGRect)rect;
@end


SWIFT_CLASS("_TtC13FrameworkDemo17SHPopMenuViewCell")
@interface SHPopMenuViewCell : UITableViewCell
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


@interface SHPopMenuViewCell (SWIFT_EXTENSION(FrameworkDemo))
/// 设置布局
- (void)layoutSubviews;
@end


SWIFT_CLASS("_TtC13FrameworkDemo13SHProgressHUD")
@interface SHProgressHUD : MBProgressHUD
- (nonnull instancetype)initWithView:(UIView * _Nonnull)view OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithWindow:(UIWindow * _Nonnull)window OBJC_DESIGNATED_INITIALIZER SWIFT_DEPRECATED;
@end






SWIFT_CLASS("_TtC13FrameworkDemo14SHQRCodeConfig")
@interface SHQRCodeConfig : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13FrameworkDemo15SHQRCodeManager")
@interface SHQRCodeManager : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13FrameworkDemo22SHQRCodeViewController")
@interface SHQRCodeViewController : SHBaseViewController
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end





@class AVCaptureOutput;
@class AVCaptureConnection;

@interface SHQRCodeViewController (SWIFT_EXTENSION(FrameworkDemo)) <AVCaptureVideoDataOutputSampleBufferDelegate>
- (void)captureOutput:(AVCaptureOutput * _Nonnull)output didOutputSampleBuffer:(CMSampleBufferRef _Nonnull)sampleBuffer fromConnection:(AVCaptureConnection * _Nonnull)connection;
@end

@class AVCaptureMetadataOutput;
@class AVMetadataObject;

@interface SHQRCodeViewController (SWIFT_EXTENSION(FrameworkDemo)) <AVCaptureMetadataOutputObjectsDelegate>
- (void)captureOutput:(AVCaptureMetadataOutput * _Nonnull)output didOutputMetadataObjects:(NSArray<AVMetadataObject *> * _Nonnull)metadataObjects fromConnection:(AVCaptureConnection * _Nonnull)connection;
@end












SWIFT_CLASS("_TtC13FrameworkDemo25SHQRCodeWebViewController")
@interface SHQRCodeWebViewController : SHBaseWebLoaderViewControoler
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


@interface SHQRCodeWebViewController (SWIFT_EXTENSION(FrameworkDemo))
- (void)webView:(WKWebView * _Nonnull)webView didFailNavigation:(WKNavigation * _Null_unspecified)navigation withError:(NSError * _Nonnull)error;
- (void)webView:(WKWebView * _Nonnull)webView didFailProvisionalNavigation:(WKNavigation * _Null_unspecified)navigation withError:(NSError * _Nonnull)error;
@end


SWIFT_CLASS("_TtC13FrameworkDemo13SHScannerView")
@interface SHScannerView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)drawRect:(CGRect)rect;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end














SWIFT_CLASS("_TtC13FrameworkDemo30SHSearchLocationViewController")
@interface SHSearchLocationViewController : SHBaseViewController
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end




@interface SHSearchLocationViewController (SWIFT_EXTENSION(FrameworkDemo)) <UISearchResultsUpdating>
- (void)updateSearchResultsForSearchController:(UISearchController * _Nonnull)searchController;
@end


@interface SHSearchLocationViewController (SWIFT_EXTENSION(FrameworkDemo)) <BMKPoiSearchDelegate>
/// 返回检索周边的结果
- (void)onGetPoiResult:(BMKPoiSearch * _Null_unspecified)searcher result:(BMKPoiResult * _Null_unspecified)poiResult errorCode:(BMKSearchErrorCode)errorCode;
@end




@interface SHSearchLocationViewController (SWIFT_EXTENSION(FrameworkDemo)) <UITableViewDataSource>
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end


@interface SHSearchLocationViewController (SWIFT_EXTENSION(FrameworkDemo)) <UITableViewDelegate>
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)scrollViewWillBeginDragging:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewDidEndDecelerating:(UIScrollView * _Nonnull)scrollView;
@end


SWIFT_CLASS("_TtC13FrameworkDemo10SHTextView")
@interface SHTextView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end





@class UITextView;

@interface SHTextView (SWIFT_EXTENSION(FrameworkDemo)) <UITextViewDelegate>
- (void)textViewDidChange:(UITextView * _Nonnull)textView;
- (BOOL)textView:(UITextView * _Nonnull)textView shouldChangeTextInRange:(NSRange)range replacementText:(NSString * _Nonnull)text SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC13FrameworkDemo7SHToast")
@interface SHToast : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end




SWIFT_CLASS("_TtC13FrameworkDemo7SHTools")
@interface SHTools : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end










SWIFT_CLASS("_TtC13FrameworkDemo14SHUpdateSource")
@interface SHUpdateSource : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end





@class WKWebViewConfiguration;

/// YMessageHandler处理从cookieOutScript发送的脚本消息
SWIFT_CLASS("_TtC13FrameworkDemo9SHWebview")
@interface SHWebview : DWKWebView
- (WKNavigation * _Nullable)loadRequest:(NSURLRequest * _Nonnull)request;
- (nonnull instancetype)initWithFrame:(CGRect)frame configuration:(WKWebViewConfiguration * _Nonnull)configuration OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


/// 微三云蓝牙功能管理
SWIFT_CLASS("_TtC13FrameworkDemo21SHWsyBluetoothManager")
@interface SHWsyBluetoothManager : NSObject
/// 当前步数
@property (nonatomic) NSInteger currentStep;
/// 连接状态
/// 0：扫描到指定蓝牙，正在连接蓝牙
/// 1：正在连接指定蓝牙设备的服务
/// 2：正在连接指定蓝牙设备的特征
/// 3：已经读取到指定的设备特征值，设备可以正常通讯
/// 4：手机蓝牙关闭或者设备已经断开连接
/// 5：设备连接出错
@property (nonatomic) NSInteger connectType;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end








SWIFT_CLASS("_TtC13FrameworkDemo10ShareAlert")
@interface ShareAlert : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




SWIFT_CLASS("_TtC13FrameworkDemo14ShareAlertView")
@interface ShareAlertView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13FrameworkDemo8ShareKit")
@interface ShareKit : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13FrameworkDemo10ShareModel")
@interface ShareModel : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




SWIFT_CLASS("_TtC13FrameworkDemo14SharePadButton")
@interface SharePadButton : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


@interface UIButton (SWIFT_EXTENSION(FrameworkDemo))
- (void)setWithImage:(UIImage * _Nullable)anImage title:(NSString * _Nullable)title titlePosition:(UIViewContentMode)titlePosition additionalSpacing:(CGFloat)additionalSpacing state:(UIControlState)state;
@end




























SWIFT_CLASS("_TtC13FrameworkDemo11UserStorage")
@interface UserStorage : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13FrameworkDemo11VideoRecord")
@interface VideoRecord : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class AVCaptureFileOutput;

@interface VideoRecord (SWIFT_EXTENSION(FrameworkDemo)) <AVCaptureFileOutputRecordingDelegate>
- (void)captureOutput:(AVCaptureFileOutput * _Nonnull)output didStartRecordingToOutputFileAtURL:(NSURL * _Nonnull)fileURL fromConnections:(NSArray<AVCaptureConnection *> * _Nonnull)connections;
- (void)captureOutput:(AVCaptureFileOutput * _Nonnull)output didFinishRecordingToOutputFileAtURL:(NSURL * _Nonnull)outputFileURL fromConnections:(NSArray<AVCaptureConnection *> * _Nonnull)connections error:(NSError * _Nullable)error;
@end


SWIFT_CLASS("_TtC13FrameworkDemo21VideoRecordController")
@interface VideoRecordController : UIViewController
@property (nonatomic, readonly) BOOL prefersStatusBarHidden;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end






SWIFT_CLASS("_TtC13FrameworkDemo15VideoRecordView")
@interface VideoRecordView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13FrameworkDemo25WKWebViewJavascriptBridge")
@interface WKWebViewJavascriptBridge : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



@class WKUserContentController;
@class WKScriptMessage;

@interface WKWebViewJavascriptBridge (SWIFT_EXTENSION(FrameworkDemo)) <WKScriptMessageHandler>
- (void)userContentController:(WKUserContentController * _Nonnull)userContentController didReceiveScriptMessage:(WKScriptMessage * _Nonnull)message;
@end




SWIFT_CLASS("_TtC13FrameworkDemo29WKWebViewJavascriptBridgeBase")
@interface WKWebViewJavascriptBridgeBase : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
